/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import koneksi.Rumahsakit;

/**
 *
 * @author Acer
 */
public class FormDokter extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDokter
     */
    public FormDokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtKdDokter = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAlamat = new javax.swing.JTextArea();
        RbLakilaki = new javax.swing.JRadioButton();
        RbPerempuan = new javax.swing.JRadioButton();
        TxtTlp = new javax.swing.JTextField();
        TxtSpesialis = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        BtnAdd = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnlClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDokter = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA DOKTER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("Kode Dokter");

        jLabel3.setText("Nama Dokter");

        jLabel4.setText("Alamat");

        jLabel5.setText("No. Telepon");

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Spesialis");

        TxtKdDokter.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtKdDokterCaretUpdate(evt);
            }
        });

        TxtAlamat.setColumns(20);
        TxtAlamat.setRows(5);
        jScrollPane2.setViewportView(TxtAlamat);

        buttonGroup1.add(RbLakilaki);
        RbLakilaki.setText("Laki-laki");

        buttonGroup1.add(RbPerempuan);
        RbPerempuan.setText("Perempuan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(TxtKdDokter))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(RbLakilaki, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(RbPerempuan))
                            .addComponent(TxtSpesialis)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TxtTlp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(TxtKdDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RbLakilaki)
                    .addComponent(RbPerempuan))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        BtnAdd.setText("ADD");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnSave.setText("SAVE");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnEdit.setText("EDIT");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        BtnDelete.setText("DELETE");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnlClose.setText("CLOSE");
        BtnlClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnlCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnlClose, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(BtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnlClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TblDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblDokter);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtKdDokterCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtKdDokterCaretUpdate
        // TODO add your handling code here:
        try {
            Connection c=Rumahsakit.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from form_dokter where kode_dokter='" + this.TxtKdDokter.getText() + "'";
            ResultSet r=s.executeQuery(sql);
            while (r.next()){
                this.TxtNama.setText(r.getString(3));
                if ("Laki-laki".equalsIgnoreCase(r.getString("jk"))){
                    RbLakilaki.setSelected(true);
                } else {
                    RbPerempuan.setSelected(true);
                }
                this.TxtAlamat.setText(r.getString("alamat"));
                this.TxtTlp.setText(r.getString("no_tlp"));
                this.TxtSpesialis.setText(r.getString("spesialis"));
            }
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi Kesalahan" + e);
        }
    }//GEN-LAST:event_TxtKdDokterCaretUpdate

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        TxtKdDokter.setText("");
        TxtNama.setText("");
        TxtAlamat.setText("");
        TxtTlp.setText("");
        buttonGroup1.clearSelection();
        TxtSpesialis.setText("");
        TxtKdDokter.requestFocus();
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        String kode_dokter=this.TxtKdDokter.getText();
        String nama=this.TxtNama.getText();
        String jk = null;
        if (RbLakilaki.isSelected()){
            jk = "Laki-Laki";
        }else if(RbPerempuan.isSelected()){
            jk = "Perempuan";
        }
        String alamat=this.TxtAlamat.getText();
        String no_tlp=this.TxtTlp.getText();
        String spesialis=this.TxtSpesialis.getText();
        if (TxtKdDokter.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Kode Dokter Tidak Boleh Kosong");
        }else {
            if(TxtNama.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nama Dokter Tidak boleh Kosong");
            }else {
                if(TxtAlamat.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Alamat Tidak Boleh Kosong");
                }else {
                    if(TxtTlp.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nomor Tlp tidak Boleh Kosong");
                    }else {
                        if(TxtSpesialis.getText().isEmpty()){
                            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Spesialis tidak Boleh Kosong");
                        }else {
                        try {
                            Connection c=Rumahsakit.getkoneksi();
                            String sql = "Insert into form_dokter values (?,?,?,?,?,?)";
                            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
                            p.setString(1, kode_dokter);
                            p.setString(2, nama);
                            p.setString(3, alamat);
                            p.setString(4, no_tlp);
                            p.setString(5, jk);
                            p.setString(6, spesialis);
                            p.executeUpdate();
                            p.close();
                            JOptionPane.showMessageDialog(this, "Sukses Tambah Data");
                        }catch(SQLException e){
                            System.out.println(e);                            
                        }finally{
                        }
                    }
                }
            }
        }try {
            Connection c=Rumahsakit.getkoneksi();
            Statement s= c.createStatement();
            String sql="select kode_dokter, nama_dokter, alamat, nohp, jk, sp from form_dokter";
            ResultSet r=s.executeQuery(sql);
            TblDokter.setModel(DbUtils.resultSetToTableModel(r));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
        String kode_dokter=this.TxtKdDokter.getText();
        String nama=this.TxtNama.getText();
        String jk = null;
        if (RbLakilaki.isSelected()){
            jk = "Laki-Laki";
        }else if(RbPerempuan.isSelected()){
            jk = "Perempuan";
        }
        String alamat=this.TxtAlamat.getText();
        String no_tlp=this.TxtTlp.getText();
        String spesialis=this.TxtSpesialis.getText();
        if (TxtKdDokter.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Kode Dokter Tidak Boleh Kosong");
        }else {
            if(TxtNama.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nama Dokter Tidak boleh Kosong");
            }else {
                if(TxtAlamat.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Alamat Tidak Boleh Kosong");
                }else {
                    if(TxtTlp.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nomor Tlp tidak Boleh Kosong");
                    }else {
                        if(TxtSpesialis.getText().isEmpty()){
                            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Spesialis tidak Boleh Kosong");
                        }else {
                        try {
                        Connection c=Rumahsakit.getkoneksi();
                        String sql = "UPDATE `form_dokter` SET `nama_dokter`=?,`alamat`=?,`nohp`=?, `jk` =?, `sp` =? where kode_dokter=?";
                        PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
                        p.setString(6, kode_dokter);
                        p.setString(1, nama);
                        p.setString(2, alamat);
                        p.setString(3, no_tlp);
                        p.setString(4, jk);
                        p.setString(5, spesialis);
                        p.executeUpdate();
                        p.close();
                        JOptionPane.showMessageDialog(this, "Sukses Update Data");
                          
                    }catch(SQLException e){
                        System.out.println(e);
                    }finally{
                    }}}}}
                        try {
                            
                            Connection c=Rumahsakit.getkoneksi();
                            Statement s= c.createStatement();
                            String sql="select kode_dokter, nama_dokter, alamat, nohp, jk, sp from form_dokter";
                            ResultSet r=s.executeQuery(sql);
                            TblDokter.setModel(DbUtils.resultSetToTableModel(r));
                    } catch (Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
        }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        String kode_dokter=this.TxtKdDokter.getText();
        try {
            Connection c=Rumahsakit.getkoneksi();
            String sql = "Delete from form_dokter where kode_dokter=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kode_dokter);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Hapus Data");
        } catch(SQLException e){
            System.out.println(e);
        } finally{
        }
            try {
                Connection c=Rumahsakit.getkoneksi();
                Statement s= c.createStatement();
                String sql="select kode_dokter, nama_dokter, alamat, nohp, jk, sp from form_dokter";
                ResultSet r=s.executeQuery(sql);
                TblDokter.setModel(DbUtils.resultSetToTableModel(r));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnlCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnlCloseActionPerformed
        // TODO add your handling code here:
        int ex = JOptionPane.showConfirmDialog(null, "Apakah anda akan keluar? ", "Anda yakin?", JOptionPane.YES_NO_OPTION);
        if (ex == 0) {
            dispose();
        }
    }//GEN-LAST:event_BtnlCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnlClose;
    private javax.swing.JRadioButton RbLakilaki;
    private javax.swing.JRadioButton RbPerempuan;
    private javax.swing.JTable TblDokter;
    private javax.swing.JTextArea TxtAlamat;
    private javax.swing.JTextField TxtKdDokter;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtSpesialis;
    private javax.swing.JTextField TxtTlp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
