/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import com.mysql.jdbc.PreparedStatement;
import koneksi.Rumahsakit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MAESYA
 */
public class FormDataPasien extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDataPasien
     */
    public FormDataPasien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtKodePasien = new javax.swing.JTextField();
        TxtNamaPasien = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAlamat = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        TxtTgl = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPasien = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        BtnAdd = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnClose = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TxtNoTlp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RBPria = new javax.swing.JRadioButton();
        RBWanita = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        TxtPekerjaan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        RBPribadi = new javax.swing.JRadioButton();
        RBBPJS = new javax.swing.JRadioButton();
        RBAsuransi = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtKet = new javax.swing.JTextArea();

        jFormattedTextField1.setText("jFormattedTextField1");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 225));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kode Pasien");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Pasien");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");

        TxtKodePasien.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtKodePasienCaretUpdate(evt);
            }
        });
        TxtKodePasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodePasienActionPerformed(evt);
            }
        });

        TxtAlamat.setColumns(20);
        TxtAlamat.setRows(5);
        jScrollPane2.setViewportView(TxtAlamat);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tanggal Berobat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TxtNamaPasien, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TxtKodePasien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TxtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtKodePasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtTgl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        TblPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblPasien);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 225));

        BtnAdd.setText("ADD");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnSave.setText("SAVE");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnEdit.setText("EDIT");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        BtnDelete.setText("DELETE");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnClose.setText("CLOSE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAdd)
                .addGap(18, 18, 18)
                .addComponent(BtnSave)
                .addGap(18, 18, 18)
                .addComponent(BtnEdit)
                .addGap(18, 18, 18)
                .addComponent(BtnDelete)
                .addGap(18, 18, 18)
                .addComponent(BtnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 225));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM DATA PASIEN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(311, 311, 311))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 225));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("No. Telepon");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");

        RBPria.setText("Laki-Laki");

        RBWanita.setText("Perempuan");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Pekerjaan");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Jaminan");

        RBPribadi.setText("Pribadi");

        RBBPJS.setText("BPJS");

        RBAsuransi.setText("Asuransi Lainnya");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Keterangan");

        TxtKet.setColumns(20);
        TxtKet.setRows(5);
        jScrollPane3.setViewportView(TxtKet);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(RBPribadi)
                        .addGap(18, 18, 18)
                        .addComponent(RBBPJS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(RBAsuransi))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(RBPria)
                                .addGap(26, 26, 26)
                                .addComponent(RBWanita))
                            .addComponent(TxtPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(TxtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RBPria)
                    .addComponent(RBWanita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(RBPribadi)
                    .addComponent(RBBPJS)
                    .addComponent(RBAsuransi))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtKodePasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodePasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKodePasienActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        TxtKodePasien.requestFocus();
        TxtNamaPasien.setText("");
        TxtAlamat.setText("");
        TxtTgl.setDate(null);
        TxtNoTlp.setText("");
        buttonGroup1.clearSelection();
        TxtPekerjaan.setText("");
        buttonGroup2.clearSelection();
        TxtKet.setText("");
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        java.util.Date tgl_berobat=(java.util.Date) this.TxtTgl.getDate();
        String kode_pasien=this.TxtKodePasien.getText();
        String nama_pasien=this.TxtNamaPasien.getText();
        String jk = null;
        if(RBPria.isSelected()){
            jk = "Laki-Laki";
        }else if (RBWanita.isSelected()){
            jk = "Perempuan";
        }
        String jaminan = null;
        if (RBPribadi.isSelected()){
            jaminan = "Pribadi";
        }else if (RBBPJS.isSelected()){
            jaminan = "BPJS";
        }else if (RBAsuransi.isSelected()){
            jaminan = "Asuransi Lainnya";
        }
        String alamat=this.TxtAlamat.getText();
        String nohp=this.TxtNoTlp.getText();
        String pekerjaan=this.TxtPekerjaan.getText();
        String keterangan=this.TxtKet.getText();
        if(TxtKodePasien.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Kode Pasien Tidak Boleh Kosong");
        }
        else{
            if (TxtNamaPasien.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nama Pasien Tidak Boleh Kosong");
            }
            else{
                if (TxtAlamat.getText().isEmpty())
                    JOptionPane.showMessageDialog(this,"Data Belum Lengkap, Alamat Tidak Boleh Kosong");
            
            else{
                if (TxtNoTlp.getText().isEmpty())
                    JOptionPane.showMessageDialog(this,"Data Belum Lengkap, Nomor Telepon Tidak Boleh Kosong");
            
            else{
                    try{
                    Connection c=Rumahsakit.getkoneksi();
                    String sql = "insert into form_pasien values(?,?,?,?,?,?,?,?,?)";
                    PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
                    p.setString(1,kode_pasien);
                    p.setString(2,nama_pasien);
                    p.setString(3,alamat);
                    p.setDate(4,new java.sql.Date(tgl_berobat.getTime()));
                    p.setString(5,nohp);
                    p.setString(6,jk);
                    p.setString(7,pekerjaan);
                    p.setString(8,jaminan);
                    p.setString(9,keterangan);
                    p.executeUpdate();
                    p.close();
                    JOptionPane.showMessageDialog(this,"Sukses Tambah Data");
                    }catch(SQLException e){
                    System.out.println(e);
                    }finally{
                    }}}
                    }
                    try{
                    Connection c=Rumahsakit.getkoneksi();
                    Statement s=c.createStatement();
                    String sql="select kode_pasien,nama_pasien,alamat,tgl_berobat,nohp,jk,pekerjaan,jaminan,keterangan from form_pasien";
                    ResultSet r=s.executeQuery(sql);
                    TblPasien.setModel(DbUtils.resultSetToTableModel(r));
                    }
                    catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                    }
                    }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void TxtKodePasienCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtKodePasienCaretUpdate
        // TODO add your handling code here:
        try{
            Connection c=Rumahsakit.getkoneksi();
            Statement s=c.createStatement();
            String sql="Select * from form_pasien where kode_pasien='" + this.TxtKodePasien.getText()+"'";
            ResultSet r=s.executeQuery(sql);
            while (r.next()){
                    this.TxtNamaPasien.setText(r.getString(3));
                   if ("Laki-Laki".equalsIgnoreCase(r.getString("jk"))){
                      RBPria.setSelected(true);
                  }else{
                    RBWanita.setSelected(true);
                  }
                  if ("Pribadi".equalsIgnoreCase(r.getString("jaminan"))){
                      RBPribadi.setSelected(true);
                  }else{
                    RBBPJS.setSelected(true);
                  }
                  {
                    RBAsuransi.setSelected(true);
                          }
                  this.TxtAlamat.setText(r.getString("alamat"));
                  this.TxtTgl.setDate(r.getDate("tgl_berobat"));
                  this.TxtNoTlp.setText(r.getString("nohp"));
            }
            r.close();
            s.close();
            }catch(SQLException e){
            System.out.print("Terjadi kesalahan" + e);
            }
    }//GEN-LAST:event_TxtKodePasienCaretUpdate

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
        java.util.Date tgl_berobat=(java.util.Date) this.TxtTgl.getDate();
        String kode_pasien=this.TxtKodePasien.getText();
        String nama_pasien=this.TxtNamaPasien.getText();
        String jk = null;
        if (RBPria.isSelected()){
            jk = "Pria";
        }else if (RBWanita.isSelected()){
            jk = "Wanita";
        }
        String jaminan = null;
        if(RBPribadi.isSelected()){
            jaminan = "Pribadi";
        }else if (RBBPJS.isSelected()){
            jaminan = "BPJS";
        }else if (RBAsuransi.isSelected()){
            jaminan = "Asuransi lainnya";}
        String alamat=this.TxtAlamat.getText();
        String nohp=this.TxtNoTlp.getText();
        String pekerjaan=this.TxtPekerjaan.getText();
        String keterangan=this.TxtKet.getText();
        if(TxtKodePasien.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nomor Identitas Pelanggan Tidak Boleh Kosong");
        }
        else{
            if (TxtNamaPasien.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Data Belum Lengkap, Nama Pelanggan Tidak Boleh Kosong");
            }
            else{
                if (TxtAlamat.getText().isEmpty())
                    JOptionPane.showMessageDialog(this,"Data Belum Lengkap, Alamat Tidak Boleh Kosong");
            
            else{
                if (TxtNoTlp.getText().isEmpty())
                    JOptionPane.showMessageDialog(this,"Data Belum Lengkap, Nomor HP Tidak Boleh Kosong");
            
            else{
                    try{
                    Connection c=Rumahsakit.getkoneksi();
                    String sql = "UPDATE `form_pasien` SET `kode_pasien`=?, `nama_pasien`=?, "
                            + "`alamat`=?,`tgl_berobat`=?, `nohp`=? `pekerjaan`=?, `jaminan`=?,"
                            + " `keterangan`=? where no_identitas=?";
                    PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
                    p.setString(9,kode_pasien);
                    p.setString(1,nama_pasien);
                    p.setString(2,alamat);
                    p.setDate(3,new java.sql.Date(tgl_berobat.getTime()));
                    p.setString(4,nohp);
                    p.setString(5,jk);
                    p.setString(6,pekerjaan);
                    p.setString(7,jaminan);
                    p.setString(8,keterangan);
                    p.executeUpdate();
                    p.close();
                    JOptionPane.showMessageDialog(this,"Sukses Tambah Data");
                    }catch(SQLException e){
                    System.out.println(e);
                    }finally{
                    }}}
                    }
                    try{
                    Connection c=Rumahsakit.getkoneksi();
                    Statement s=c.createStatement();
                    String sql="select kode_pasien,nama_pasien,alamat,tgl_berobat,nohp,jk,pekerjaan,jaminan,keterangan from form_pasien";
                    ResultSet r=s.executeQuery(sql);
                    TblPasien.setModel(DbUtils.resultSetToTableModel(r));
                    }
                    catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                    }
                    }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        java.util.Date tgl_berobat=(java.util.Date) this.TxtTgl.getDate();
        String kode_pasien=this.TxtKodePasien.getText();
        try{
            Connection c=Rumahsakit.getkoneksi();
            String sql="Delete from form_pasien Where kode_pasien=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kode_pasien);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this,"Sukses Hapus Data");
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            
        }try{
            Connection c=Rumahsakit.getkoneksi();
            Statement s=c.createStatement();
            String sql="select kode_pasien,nama_pasien,alamat,tgl_berobat,nohp,jk,pekerjaan,jaminan,keterangan from form_pasien";
            ResultSet r=s.executeQuery(sql);
            TblPasien.setModel(DbUtils.resultSetToTableModel(r));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_BtnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnSave;
    private javax.swing.JRadioButton RBAsuransi;
    private javax.swing.JRadioButton RBBPJS;
    private javax.swing.JRadioButton RBPria;
    private javax.swing.JRadioButton RBPribadi;
    private javax.swing.JRadioButton RBWanita;
    private javax.swing.JTable TblPasien;
    private javax.swing.JTextArea TxtAlamat;
    private javax.swing.JTextArea TxtKet;
    private javax.swing.JTextField TxtKodePasien;
    private javax.swing.JTextField TxtNamaPasien;
    private javax.swing.JTextField TxtNoTlp;
    private javax.swing.JTextField TxtPekerjaan;
    private com.toedter.calendar.JDateChooser TxtTgl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
